### ISSUE TITLE
Cannot declare a parameter named 'selector'  in strict mode

### ISSUE THREAD

**Issue by keripix** [TylorS/snabbdom-selector#13]
I tried to use this tool by following the instruction:

```
import {select} from "snabbdom-selector";
```

But I got this error every tiime I run the unit test:

`SyntaxError: Cannot declare a parameter named 'selector'  in strict mode`

I use karma, and below is the configuration for the preprocessor:

```
preprocessors: {
    './**/*.spec.js': ['browserify']
},

browserify: {
    transform: [
        'browserify-shim',
        ["babelify", { "presets": ["latest"] }]
    ]
}
```

Could you please help me solve this problem? Is there any information that you need so that this report could be more useful?

Thanks in advance

**Comment by atomrc** [comment]
Fixed in `v2.0.1`
