### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'isBuffer' of undefined

### ISSUE THREAD

**Issue by chenxeed** [TylorS/snabbdom-selector#17]
Hi!

I tried to use the library in my webpack precompiler.
The precompile is success, however when I tried to run it in my browser, it appears:

```
util.js:103 Uncaught (in promise) TypeError: Cannot read property 'isBuffer' of undefined
```

that seems like coming from webpack. Is there any configuration I need to do to make this lib working in webpack?

Much appreciated.

**Comment by TylorS** [comment]
Hello @chenxeed 

I'm never encountered this issue before. Is it coming from a particular plugin of some sort?

**Comment by chenxeed** [comment]
It happened when I tried to import 'snabbdom-selector' in my JS file.

```
import { select } from 'snabbdom-selector';
```

I'm using webpack 2, npm 5.0.3. Hopefully it helps.

**Comment by FeliciousX** [comment]
i think this happens because if we try to run `snabbdom-selector` in a browser environment it would fail.

@TylorS have you tried using this on a browser environment? or only on node environment for testing?

**Comment by TylorS** [comment]
I built it initially as a testing tool. But if people need it in a browser, I'm sure we can figure out the solution

**Comment by FeliciousX** [comment]
probably related to https://github.com/TylorS/snabbdom-selector/issues/18

**Comment by jvanbruegge** [comment]
With #26 it is possible to run in the browser

**Comment by jvanbruegge** [comment]
bzw @atomrc, this can be closed now

**Comment by atomrc** [comment]
Ah nice. Thanks @jvanbruegge for the ping.
