### ISSUE TITLE
Attribute selectors not working

### ISSUE THREAD

**Issue by nlarche** [TylorS/snabbdom-selector#27]
Hello, 

With the version "3.0.0", attribute selector like `"div[name=test]"` are not working anymore. 
data-attribute (`[data-test]`) are not working either.

```
import { toVNode } from "snabbdom/tovnode";
import { select } from "snabbdom-selector";

document.getElementById("app").innerHTML = `
<div data-test class="test" name="test">
</div>
`;

const vnodes = toVNode(document.getElementById("app"));

console.log(select(".test", vnodes)); // [div]
console.log(select("[data-test]", vnodes)); // []
console.log(select("div[name=test]", vnodes)); // []
```

here are 2 exemples 
- with snabbdom-selector 3.0.0 : https://codesandbox.io/s/8nrv6zvw69
- with snabbdom-selector 2.0.1: https://codesandbox.io/s/vqrr6rkl9y

I think this is related to the new added package 'tree-selector'

**Comment by atomrc** [comment]
Hey @nlarche thanks for the report.
This is even weirder that there actually is a test that covers this scenario https://github.com/TylorS/snabbdom-selector/blob/master/test/index.ts#L131

@jvanbruegge any idea what could be the problem here. Could it be in `tree-selector`?

**Comment by jvanbruegge** [comment]
I think i know why the second one, the data selector is not working. I it how snabbdom-selector configures tree-selector.
But at least the last one (pure attr) should work.

**Comment by jvanbruegge** [comment]
Oh, i see, your third one needs quotes

**Comment by jvanbruegge** [comment]
Ok, I checked, `document.querySelector` accepts strings without quotes. So the third selector not working is an issue in `tree-selector`
